module Logic.App.Utils.LetterMap exposing (..)
import Logic.App.Types exposing (Direction(..))

letterMap : List ( String, ( Direction, Direction ) )
letterMap =
    [ ( "w", ( East, East ) )
    , ( "a", ( East, Northwest ) )
    , ( "q", ( East, Northeast ) )
    , ( "d", ( East, Southwest ) )
    , ( "e", ( East, Southeast ) )
    , ( "e", ( Northeast, East ) )
    , ( "q", ( Northeast, Northwest ) )
    , ( "a", ( Northeast, West ) )
    , ( "w", ( Northeast, Northeast ) )
    , ( "d", ( Northeast, Southeast ) )
    , ( "d", ( Northwest, East ) )
    , ( "w", ( Northwest, Northwest ) )
    , ( "q", ( Northwest, West ) )
    , ( "e", ( Northwest, Northeast ) )
    , ( "a", ( Northwest, Southwest ) )
    , ( "d", ( West, Northeast ) )
    , ( "e", ( West, Northwest ) )
    , ( "w", ( West, West ) )
    , ( "a", ( West, Southeast ) )
    , ( "q", ( West, Southwest ) )
    , ( "a", ( Southwest, East ) )
    , ( "d", ( Southwest, Northwest ) )
    , ( "e", ( Southwest, West ) )
    , ( "q", ( Southwest, Southeast ) )
    , ( "w", ( Southwest, Southwest ) )
    , ( "q", ( Southeast, East ) )
    , ( "a", ( Southeast, Northeast ) )
    , ( "d", ( Southeast, West ) )
    , ( "w", ( Southeast, Southeast ) )
    , ( "e", ( Southeast, Southwest ) )
    ]